export * from './about/about';
export * from './contact/contact';
export * from './home/home';
export * from './list/list';
export * from './login/login';
export * from './register/register';
export * from './tabs/tabs';
export * from './welcome/welcome';
export * from './request/request';